### ISSUE TITLE
Route to view unsortedlist errors on return

### ISSUE THREAD

**Issue by dgolant** [blackbetty/EverythingisX#1]
The following code is throwing a `raise ValueError('View function did not return a response')` error because the return is empty.  I am guessing it's empty because the changes to it only occur inside the context manager??

```python
@app.route('/unsortedlist')
def list_articles():
	lines = None
	with sql_execute("SELECT * FROM UnsortedArticles") as result:
		lines = "<br/>".join.join(build_url_list(result))
	return lines
```

For reference, the following returns the same error 

```python
@app.route('/unsortedlist')
def list_articles():
	lines = None
	with sql_execute("SELECT * FROM UnsortedArticles") as result:
		lines = "<br/>".join.join(build_url_list(result))
	        return lines
```

@jlward

**Comment by jlward** [comment]
I don't know flask well enough to know what `@app.route` expects back to build a response. Independent of that however, you have `lines = "<br/>".join.join(...` which is probably causing a problem. In django this would result in a 500 (status code). Since you are calling `join` a second time (on the first `join`) you are going to have a problem. You'll probably get some sort of `TypeError` or something like that. Since the method `join` doesn't have a method `join`. It's possible that fixing this will fix your problem. I'm not certain.

If that doesn't fix it, can you link the line of code this is at? If I recall, we committed the original before committing these changes, so I'll be able to look back and see if anything wonky has changed with my suggested changes.

**Comment by dgolant** [comment]
-_- How did I miss that... I will give it a shot tonight.  I will link back if that doesn't work.

**Comment by dgolant** [comment]
Part of it was that, part was that the result variable was a SQL alchemy Result object, that I had to convert into a list of dicts, and then fix the build_url_list function. It's all in the most recent commit if you are curious to take a look, but it's fairly mundane.
